"""make record_items.score nullable

Revision ID: 0a1872fc7e4a
Revises: cc4b5dcdd857
Create Date: 2026-03-29 23:39:43.830921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1872fc7e4a'
down_revision: Union[str, Sequence[str], None] = 'cc4b5dcdd857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record_items', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record_items', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
