"""add_record_items_restructure_photos

Revision ID: f464dcce400d
Revises: 0daeba5f2cc5
Create Date: 2026-03-04 10:31:10.119719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f464dcce400d'
down_revision: Union[str, Sequence[str], None] = '0daeba5f2cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.Integer(), nullable=False),
    sa.Column('song_name', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'chart_id', name='uq_record_item')
    )
    op.alter_column('participants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('participants_user_id_fkey'), 'participants', type_='foreignkey')
    op.create_foreign_key(None, 'participants', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('photos', sa.Column('record_item_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('photos_chart_id_fkey'), 'photos', type_='foreignkey')
    op.drop_constraint(op.f('photos_record_id_fkey'), 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'record_items', ['record_item_id'], ['id'])
    op.drop_column('photos', 'record_id')
    op.drop_column('photos', 'score')
    op.drop_column('photos', 'chart_id')
    op.alter_column('records', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('records_user_id_fkey'), 'records', type_='foreignkey')
    op.create_foreign_key(None, 'records', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.create_foreign_key(op.f('records_user_id_fkey'), 'records', 'users', ['user_id'], ['id'])
    op.alter_column('records', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('photos', sa.Column('chart_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('photos', sa.Column('score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('photos', sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key(op.f('photos_record_id_fkey'), 'photos', 'records', ['record_id'], ['id'])
    op.create_foreign_key(op.f('photos_chart_id_fkey'), 'photos', 'charts', ['chart_id'], ['id'])
    op.drop_column('photos', 'record_item_id')
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.create_foreign_key(op.f('participants_user_id_fkey'), 'participants', 'users', ['user_id'], ['id'])
    op.alter_column('participants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('record_items')
    # ### end Alembic commands ###
